apiVersion: v2
name: onecx-k8s-db-postgresql-operator
version: 0.0.0
appVersion: 0.0.0
description: Onecx k8s postgresql database schema operator
keywords:
  - postgresql
  - k8s
  - operator
sources:
  - https://github.com/onecx/onecx-k8s-db-postgresql-operator
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: 0.41.0
    repository: oci://ghcr.io/onecx/charts
