app:
  name: db-postgresql-operator
  image:
    repository: "onecx/onecx-k8s-db-postgresql-operator"
  db:
    enabled: true
    operator: false
  envCustom:
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  serviceAccount:
    enabled: true
