apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.name }}-cluster-role
rules:
  - apiGroups:
      - onecx.github.io
    resources:
      - databases
      - databases/status
      - databases/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete